version: 2
updates:
  # npm(pnpm)パッケージの定期アップデート設定
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    timezone: "Asia/Tokyo"
    labels:
      - "dependencies"

  # GitHub Actionsのバージョン定期アップデート設定
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
    # Actionのメジャー/マイナーアップデートも自動検知します
